server:
    port: 8080
camel:
    springboot:
        name: ServicesRest
    component:
        servlet:
            mapping:
                contextPath: /ecommapp/*
management:
    port: 8081
endpoints:
    enabled: true
    health:
        enabled: true
quickstart:
    generateOrderPeriod: 10s
    processOrderPeriod: 30s

baeldung:
    api:
        path: '/ecommapp'
